#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
def algoritmos():
	print(" ===========================================================================")
	print("|            SCRIPTS PARA AUTOMATIZAR UN ANALISIS FORENSE                   |")
	print("|        SINTAXIS: python main.py <script>                                  |")
	print("| <Scripts>:                                                                |")
	print("|              -em Esterilizacion de un medio                               |")
	print("|              -oi Obtener imagen de un pendrive                            |")
	print("|              -mi montar imagen                                            |")
	print("|              -oh Obtener el Hash                                          |")
	print("|              -ch Comparar Hash                                            |")
	print("|              -ba Buscar Archivos y Direcctorios                           |")
	print("|              -bc Búsqueda de cadenas                                      |")
	print("|              -ra Recuperar Archivos                                       |")
	print("|              -at Analizar Trafico de Red                                  |")
	print("|              -ai Analisis de archivos infectados                          |")
	print("|              -dc Diligenciar la cadena de custodia                        |")
	print(" ===========================================================================")
	print("Consultar la ayuda de un Script:")
	print("                         	SINTAXIS:")
	print("                                      python main.py <Script>")
def ayudaesterilizar():
	print("===================================ESTERILIZAR UN MEDIO==============================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -em Dispositivo tamañoBloque Nombre Iteraciones                                     |")
	print("|                                                                                                    |")
	print("| Dispositivo: Dirección donde esta montada el Dispositivo, df -h para obtenerla                     |")
	print("| tamañoBloque: tamaño de los bloques, fdisk -l 'ruta' para obtenerlo o 512 por defecto              |")
	print("| Nombre: nombre que se le asignara al Dispositivo despues de formatear                              |")
	print("| Iteraciones: Numero de iteraciones para rellenar con ceros y numeros aleatorios el Dispositivo     |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -em /dev/sdb1 512 Mi-USB 99                                                         |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")

def ayudaObtenerImagen():
	print("====================================OBTENER IMAGEN DE UN PENDRIVE=====================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -oi Dispositivo NombreImagen                                                        |")
	print("|                                                                                                    |")
	print("| Dispositivo: Dirección donde esta montada el Dispositivo, df -h para obtenerla                     |")
	print("| NombreImagen: Nombre con el que se crearà la imagen                                                |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -oi /dev/sdb1 imagen.img                                                            |")
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaMontarImagen():
	print("============================================MONTAR IMAGEN=============================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -mi NombreImagen PointMount                                                         |")
	print("|                                                                                                    |")
	print("| NombreImagen: Nombre de la imagen que se va a montar                                               |")
	print("| PointMount: Dirección donde se va a montar la imagen                                               |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -oi imagen.img /root/Documents/PointMount                                           |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")

def ayudaObtenerHash():
	print("====================================OBTENER HASH DE UN ARCHIVO========================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -oh Archivo                                                                         |")
	print("|                                                                                                    |")
	print("| Archivo: Archivo al que se le obtendrà el hash                                                     |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -oh quijote.txt                                                                     |")	
	print("| Ejemplo hash miltiple archivos:                                                                    |")
	print("| python main.py -ohr /root/Documents                                                                |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaCompararHash():
	print("=======================================COMPARAR HASH DE UN ARCHIVO====================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -ch Archivo ArchivoVerificaciòn                                                     |")
	print("|                                                                                                    |")
	print("| Archivo: Dirección al que se le obtendrà el hash                                                   |")
	print("| ArchivoVerificaciòn: Archivo que contiene el hash de verificaciòn                                  |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -ch quijote.txt hashQuijot.txt                                                      |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaBuscarArchivos():
	print("=========================================BUSCAR NOMBRES DE ARCHIVOS===================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -ba ruta datos                                                                      |")
	print("|                                                                                                    |")
	print("| ruta: ruta donde se va a buscar                                                                    |")
	print("| datos: archivo que contiene las cadenas que pueden ser nombre de archivos importantes              |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py /root/Documents datos.txt                                                           |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaBuscarCadenas():
	print("=========================================BUSCAR CADENAS EN ARCHIVOS===================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -bc ArchivoCadenas ArchivoBuscar                                                    |")
	print("|                                                                                                    |")
	print("| ArchivoCadenas: Archivo donde estan las cadenas que se desean buscar                               |")
	print("| ArchivoBuscar: Archivo o Directorio donde se desea buscar                                          |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -bc Cadenas.txt /root/Documents/quijote.txt                                         |")	
	print("| python main.py -bcr Cadenas.txt /root/Documents                                                     |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaRecuperarArchivos():
	print("========================================Recuperar archivos===========================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -ra Extensión volumen directorio                                                    |")
	print("| python main.py -raa volumen directorio                                                             |")
	print("|                                                                                                    |")
	print("| Para hacer uso de este script se debe instalar la aplicacion foremost                              |")
	print("| Extensión: Hace referencia a la extencion del tipo de Archivo que quiere recuperar                 |")
	print("| volumen: volumen de donde se va a recuperar los archivos                                           |")
	print("| directorio: directorio en el cual se va a guardar los resultado(debe estar vacio)                  |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -ra pdf /dev/sdb /home/forense/Documentos/carving/                                  |")
	print("| python main.py -raa /dev/sdb /home/forense/Documentos/carving/                                     |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaAnalisisTrafico():
	print("================================================MENU=================================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -at CapturaTráfico                                                                  |")
	print("|                                                                                                    |")
	print("| CapturaTrafico: Archivo de captura de tráfico                                                      |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -at captura                                                                         |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaAnalisisInfectados():
	print("==============================BUSCAR POSIBLES ARCHIVOS INFEECTADOS====================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -ai Archivo                                                                         |")
	print("|                                                                                                    |")
	print("| Archivo: Archivo que se va a analizar si esta infectado                                            |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -ai Archivo.zip                                                                     |")	
	print("| Ejemplo recursivo:                                                                                 |")
	print("| python main.py -air /root/Documents                                                                |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaDiligenicarCadena():
	print("=================================DILIGENCIAR CADENA DE CUSTODIA=======================================")
	print("| Sintaxis:                                                                                          |")
	print("| python main.py -dc Ruta                                                                            |")
	print("| python main.py -dcv Ruta (Formato solo con la tabla de evidencia llena)                            |")
	print("|                                                                                                    |")
	print("| Ruta: Es la direccion del directorio donde se encuentran los ficheros los cuales son evidencia     |")
	print("|====================================================================================================|")
	print("| Ejemplo:                                                                                           |")
	print("| python main.py -dc /home/forense/Descargas/FORENSE-PARCIAL3/                                       |")	
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
def ayudaMenu():
	print("======================SOFTWARE Y LIBRERÍAS NECESARIAS PARA EL USO DEL SCRIPT=========================")
	print("| Librerias de python:                                                                               |")
	print("| virustotal                                                                                         |")
	print("| python-docx                                                                                        |")
	print("|                                                                                                    |")
	print("| Software:                                                                                          |")
	print("| foremost                                                                                           |")
	print("| tshark                                                                                             |")
	print("|                                                                                                    |")
	print("|====================================================================================================|")
	print("| Comandos para instalar librerias y Software necesario:                                             |")
	print("|                                                                                                    |")
	print("| pip install virustotal-api                                                                         |")	
	print("| pip install python-docx                                                                            |")
	print("| apt-get install foremost                                                                           |")
	print("| apt-get install wireshark                                                                          |")
	print("|                                                                                                    |")
	print("| Nota: Para algunas herramientas es necesario tener permisos de root                                |")
	print("|====================================================================================================|")
	print("| Creado por: Davinson Mellizo y Cesar Augusto Daza                                                  |")
	print("| Correo: davinsonmellizo@unicauca.edu.co - cesardaza@unicauca.edu.co                                |")
	print("| Profesor: Siler Amador Donado                                                                      |")
	print("| Fecha: 05/08/2019                                                                                  |")
	print("| Repositorio: https://github.com/davinsonMellizo/FORENSE-PARCIAL3.git                               |")
	print("=====================================================================================================")
